project_name: "Nuclear_Data_Inference_2025"
output_dir: "data/mcmc_chains/"
figures_dir: "reports/figures/cr_53_20r_int_1000pcm/"

# -----------------------------------------------------------------------------
# Global Defaults (Apply to all experiments unless overridden)
# -----------------------------------------------------------------------------
defaults:
  gp:
    kernel: "RBF"          # Options: RBF, Matern52, RationalQuadratic
    normalize_y: false     # Standardize output data before training
    n_restarts: 10         # Optimization restarts for GP hyperparameters
  
  mcmc:
    sampler: "emcee"
    n_walkers: 10
    n_steps: 5000
    burn_in: 1000
    random_seed: 102

# -----------------------------------------------------------------------------
# Prior Information
# -----------------------------------------------------------------------------
parameters:
  names: ["Cr53_Gg4keV"]
  # prior_means: [3.08939406]
  prior_means: [4.14]
  prior_stds: [0.20]

# -----------------------------------------------------------------------------
# Experiment Definitions
# -----------------------------------------------------------------------------
experiments:
  - id: "pmi002"
    title: "PMI002"
    description: "PU-MET-INTER-002 using stainless steel reflector"
    type: "integral"
    
    training_data:
      input_path: "data/processed/pmi002/pmi002_inputs.csv"
      output_path: "data/processed/pmi002/pmi002_outputs.csv"
    
    experimental_data:
      measurement: 0.98780
      uncertainty: 0.01230

  - id: "hmi001"
    title: "HMI001"
    description: "Stainless steel reflector"
    type: "integral"
      
    training_data:
      input_path: "data/processed/hmi001/hmi001_inputs.csv"
      output_path: "data/processed/hmi001/hmi001_outputs.csv"
      
    experimental_data:
      measurement: 0.99600
      uncertainty: 0.01260

  - id: "cr53_thin"
    title: "nTOF Cr53 thin (2022)"
    description: "Time-of-Flight measurement performed in nTOF (CERN) by Pablo Perez et at. using thin Cr-53 target"
    type: "microscopic" # microscopic assumes your output is based on chi-squared
    gp_override:
      kernel: "Quadratic"
      
    training_data:
      input_path: "data/processed/ntof-jeff40/ntof_inputs.csv"
      output_path: "data/processed/ntof-jeff40/ntof_outputs.csv" # Using reduced chi-squared statistic
      C_constant: 10.330074020916287 # -0.5 * (np.log(2 * np.pi * df_lst['dx'].mean()**2))
      # C_constant: 2644.498949354568